language: rust

rust:
  - stable
  - nightly

matrix:
  fast_finish: true

before_script:
  - if [ "$TRAVIS_RUST_VERSION" = "nightly" ]; then rustup component add rustfmt; fi

script:
  - cargo build
  - if [ "$TRAVIS_RUST_VERSION" = "nightly" ]; then cargo test; fi
  - if [ "$TRAVIS_RUST_VERSION" = "nightly" ]; then cargo fmt --all -- --check; fi
