language: rust

rust:
  - stable
  - nightly

matrix:
  fast_finish: true
  include:
    - rust: 'stable'
      env: TESTS=false
    - rust: 'nightly'
      env: TESTS=true

script:
  - cargo build --verbose --all
  - env TESTS cargo test --verbose --all

