name: .

args:
  - config:
      short: c
      long: config
      value_name: FILE
      help: Sets a custom config file
      takes_value: true

  - verbose:
      short: v
      multiple: true
      help: Sets the level of verbosity

subcommands:
  - run:
      about: Run installed program
      args:
        - name:
            required: true
            index: 1
            help: Program name

  - remove:
      about: Remove program, container, build
      args:
        - name:
            required: true
            index: 1
            help: Program name

  - list:
      about: Show installed programs with their containers

  - test:
      about: Test compatibility and feature access

  - create:
      about: Create new docker build for existed package
      args:
        - package:
            required: true
            index: 1
            help: Path to .deb package
        - command:
            long: command
            takes_value: true
            help: Custom command to run
        - dependencies:
            long: dependencies
            takes_value: true
            help: Additional dependencies to install
        - display:
            short: d
            long: display
            help: Share host display
        - sound:
            short: s
            long: sound
            help: Share sound device
        - home:
            short: h
            long: home
            help: Mount home directory
